/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Default docs sidebar (plugin expects this id when routeBasePath is "/")
  docs: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/introduction",
        "getting-started/quick-start",
        "getting-started/tutorial",
        {
          type: "category",
          label: "Installation",
          items: [
            { type: "autogenerated", dirName: "getting-started/installation" },
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Upgrade",
          items: [
            { type: "autogenerated", dirName: "getting-started/upgrade" },
          ],
          collapsed: true,
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Concepts",
      items: [{ type: "autogenerated", dirName: "concepts" }],
      collapsed: false,
    },
    {
      type: "category",
      label: "BYOC",
      link: {
        type: "doc",
        id: "byoc/index",
      },
      items: [
        "byoc/how-it-works",
        "byoc/backends",
        "byoc/configure-kubernetes",
        "byoc/verify",
        "byoc/use-traffic",
        {
          type: "category",
          label: "Examples",
          link: { type: "doc", id: "byoc/examples/index" },
          items: ["byoc/examples/ecs"],
          collapsed: true,
        },
        "byoc/troubleshooting",
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "doc",
        id: "guides/index",
      },
      items: [
        "guides/ai-assistant",
        {
          type: "category",
          label: "Traffic Capture",
          items: [{ type: "autogenerated", dirName: "guides/capture" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Traffic Transformation",
          items: [{ type: "autogenerated", dirName: "guides/transformation" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Traffic Replay",
          items: [
            { type: "autogenerated", dirName: "guides/replay" },
            { type: "autogenerated", dirName: "guides/reports" },
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Service Mocking",
          items: [{ type: "autogenerated", dirName: "guides/mocking" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Databases",
          link: { type: "doc", id: "guides/databases/index" },
          items: ["guides/databases/mock-a-database"],
          collapsed: true,
        },
        {
          type: "category",
          label: "Data Loss Prevention",
          items: [{ type: "autogenerated", dirName: "guides/dlp" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Integrations",
          items: [{ type: "autogenerated", dirName: "guides/integrations" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Advanced Topics",
          items: [
            { type: "autogenerated", dirName: "guides/message-brokers" },
            {
              type: "category",
              label: "GraphQL",
              link: { type: "doc", id: "guides/graphql/index" },
              items: [
                "guides/graphql/semantic-paths",
                "guides/graphql/editing",
                "guides/graphql/recipes",
              ],
              collapsed: true,
            },
            "guides/end-to-end",
            "guides/production-readiness",
            "guides/browser",
            "guides/json-payloads",
            "guides/tls",
            "guides/ingress",
            "guides/prometheus",
            "guides/signature-refinement-guide",
            "guides/local-capture",
            "guides/manual_snapshot",
            "guides/identify-session",
            "guides/extract-replace",
            "guides/creating-a-snapshot",
            "guides/creating-filters",
            "guides/recommendations",
            "guides/resend-rrpair",
            "guides/cluster-map",
            "guides/compare-rrpairs",
            "guides/websocket",
            "guides/cli",
            "guides/load-patterns",
            "guides/troubleshooting",
          ],
          collapsed: true,
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Local Development",
      items: [
        "proxymock/index",
        {
          type: "category",
          label: "Agent Tutorial: On Your Machine",
          link: { type: "doc", id: "proxymock/agent-tutorial/index" },
          items: [
            "proxymock/agent-tutorial/install-proxymock",
            "proxymock/agent-tutorial/run-the-demo-app",
            "proxymock/agent-tutorial/record-traffic",
            "proxymock/agent-tutorial/tune-the-mocks",
            "proxymock/agent-tutorial/tune-the-tests",
            "proxymock/agent-tutorial/regression-test",
            "proxymock/agent-tutorial/performance-test",
            "proxymock/agent-tutorial/your-own-service",
          ],
          collapsed: false,
        },
        {
          type: "category",
          label: "Agent Tutorial: In Your Cluster",
          link: { type: "doc", id: "proxymock/agent-tutorial-cluster/index" },
          items: [
            "proxymock/agent-tutorial-cluster/install-the-operator",
            "proxymock/agent-tutorial-cluster/deploy-the-demo-app",
            "proxymock/agent-tutorial-cluster/record-traffic",
            "proxymock/agent-tutorial-cluster/replay-the-tests",
            "proxymock/agent-tutorial-cluster/tune-the-mocks",
            "proxymock/agent-tutorial-cluster/regression-test",
            "proxymock/agent-tutorial-cluster/performance-test",
            "proxymock/agent-tutorial-cluster/your-own-workload",
          ],
          collapsed: false,
        },
        "proxymock/agent-skills",
        {
          type: "category",
          label: "Manual Workflows",
          items: [
            "proxymock/getting-started/installation",
            {
              type: "category",
              label: "Quickstart",
              items: [
                "proxymock/getting-started/quickstart/local/index",
                "proxymock/getting-started/quickstart/in-cluster/index",
                "proxymock/getting-started/quickstart/live-tail/index",
              ],
              collapsed: true,
            },
            "proxymock/getting-started/faq",
            "proxymock/getting-started/help",
            "proxymock/getting-started/language-reference",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "How It Works",
          items: [{ type: "autogenerated", dirName: "proxymock/how-it-works" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Guides",
          items: [{ type: "autogenerated", dirName: "proxymock/guides" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Databases",
          link: { type: "doc", id: "proxymock/databases/index" },
          items: [
            {
              type: "category",
              label: "Record your database",
              items: [
                "proxymock/databases/record/postgresql",
                "proxymock/databases/record/mysql",
                "proxymock/databases/record/mongodb",
                "proxymock/databases/record/redis",
                { type: "link", label: "DynamoDB", href: "/proxymock/aws/dynamodb/" },
              ],
              collapsed: true,
            },
            "proxymock/databases/sql-compare",
            "proxymock/databases/link-queries-to-requests",
            "proxymock/databases/load-and-regression-testing",
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "AWS",
          items: [{ type: "autogenerated", dirName: "proxymock/aws" }],
          collapsed: true,
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Reference",
      items: [{ type: "autogenerated", dirName: "reference" }],
      collapsed: true,
    },
    {
      type: "category",
      label: "QABot",
      items: [{ type: "autogenerated", dirName: "qabot" }],
      collapsed: true,
    },
    {
      type: "category",
      label: "Security",
      items: [{ type: "autogenerated", dirName: "security" }],
      collapsed: true,
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
