/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/introduction",
        "getting-started/quick-start",
        "getting-started/tutorial",
        {
          type: "category",
          label: "Installation",
          items: [{ type: "autogenerated", dirName: "getting-started/installation" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Upgrade",
          items: [{ type: "autogenerated", dirName: "getting-started/upgrade" }],
          collapsed: true,
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Concepts",
      items: [{ type: "autogenerated", dirName: "concepts" }],
      collapsed: false,
    },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "doc",
        id: "guides/index"
      },
      items: [
        {
          type: "category",
          label: "Traffic Capture",
          items: [{ type: "autogenerated", dirName: "guides/capture" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Traffic Transformation",
          items: [{ type: "autogenerated", dirName: "guides/transformation" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Traffic Replay",
          items: [
            { type: "autogenerated", dirName: "guides/replay" },
            { type: "autogenerated", dirName: "guides/reports" },
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "Service Mocking",
          items: [{ type: "autogenerated", dirName: "guides/mocking" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Data Loss Prevention",
          items: [{ type: "autogenerated", dirName: "guides/dlp" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Integrations",
          items: [{ type: "autogenerated", dirName: "guides/integrations" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Advanced Topics",
          items: [
            { type: "autogenerated", dirName: "guides/message-brokers" },
            "guides/graphql",
            "guides/end-to-end",
            "guides/production-readiness",
            "guides/browser",
            "guides/json-payloads",
            "guides/tls",
            "guides/ingress",
            "guides/prometheus",
            "guides/signature-refinement-guide",
            "guides/local-capture",
            "guides/manual_snapshot",
            "guides/identify-session",
            "guides/extract-replace",
            "guides/creating-a-snapshot",
            "guides/creating-filters",
            "guides/cli",
            "guides/dlp",
            "guides/load-patterns",
            "guides/troubleshooting",
          ],
          collapsed: true,
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Local Development (AI)",
      items: [
        "proxymock/index",
        {
          type: "category",
          label: "Getting Started",
          items: [
            "proxymock/getting-started/installation",
            "proxymock/getting-started/faq",
            "proxymock/getting-started/help",
            "proxymock/getting-started/language-reference",
            {
              type: "category",
              label: "Quickstart",
              items: [
                "proxymock/getting-started/quickstart/index",
                "proxymock/getting-started/quickstart/quickstart-cli",
                "proxymock/getting-started/quickstart/quickstart-mcp",
              ],
              collapsed: true,
            },
          ],
          collapsed: true,
        },
        {
          type: "category",
          label: "How It Works",
          items: [{ type: "autogenerated", dirName: "proxymock/how-it-works" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "Guides",
          items: [{ type: "autogenerated", dirName: "proxymock/guides" }],
          collapsed: true,
        },
        {
          type: "category",
          label: "AWS",
          items: [{ type: "autogenerated", dirName: "proxymock/aws" }],
          collapsed: true,
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Reference",
      items: [{ type: "autogenerated", dirName: "reference" }],
      collapsed: true,
    },
    {
      type: "category",
      label: "QABot",
      items: [{ type: "autogenerated", dirName: "qabot" }],
      collapsed: true,
    },
    {
      type: "category",
      label: "Security",
      items: [{ type: "autogenerated", dirName: "security" }],
      collapsed: true,
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
