import assert from "node:assert/strict";
import test from "node:test";

import {
  analyzeFile,
  parseAddedLines,
} from "../validation/check-public-writing.mjs";

const allLines = (content) =>
  new Set(content.split("\n").map((_, index) => index + 1));

test("ignores violations on untouched lines", () => {
  const content = "SpeedScale is misspelled.\n\nThis line changed.\n";
  assert.deepEqual(
    analyzeFile("docs/example.md", content, new Set([3])),
    [],
  );
});

test("blocks objective terminology and capitalization violations", () => {
  const content = "Proxymock uses ground truth from Home Depot.\n";
  const findings = analyzeFile(
    "docs/example.md",
    content,
    allLines(content),
  );
  assert.deepEqual(
    findings.map((finding) => finding.rule),
    ["confidential customer", "product capitalization", "retired terminology"],
  );
});

test("blocks hard-wrapped prose on changed lines", () => {
  const content =
    "This paragraph was wrapped even though it is prose\nthat should remain on one source line.\n";
  const findings = analyzeFile(
    "docs/example.md",
    content,
    allLines(content),
  );
  assert.equal(
    findings.filter((finding) => finding.rule === "hard-wrapped prose").length,
    2,
  );
});

test("allows separate paragraphs and list items", () => {
  const content =
    "First paragraph.\n\nSecond paragraph.\n\n- First item\n- Second item\n";
  assert.equal(
    analyzeFile("docs/example.md", content, allLines(content)).length,
    0,
  );
});

test("ignores fenced and inline code", () => {
  const content =
    "```text\nSpeedScale and Home Depot\n```\nUse `SpeedScale` as test input.\n";
  assert.equal(
    analyzeFile("docs/example.md", content, allLines(content)).length,
    0,
  );
});

test("blocks an em dash anywhere in public prose", () => {
  const opening = "Opening sentence — with a dash.\n";
  const later = `${Array.from({ length: 10 }, (_, index) => `Sentence ${index + 1}.`).join(" ")} Later sentence — blocked here too.\n`;
  assert.equal(
    analyzeFile(
      "docs/example.md",
      opening,
      allLines(opening),
    )[0].rule,
    "em dash",
  );
  assert.equal(
    analyzeFile("docs/example.md", later, allLines(later))[0].rule,
    "em dash",
  );
});

test("reports style patterns as warnings", () => {
  const content = "Moreover, this robust system can leverage existing tools.\n";
  const findings = analyzeFile(
    "docs/example.md",
    content,
    allLines(content),
  );
  assert.ok(findings.length >= 3);
  assert.ok(findings.every((finding) => finding.severity === "warning"));
});

test("checks visible Docusaurus frontmatter", () => {
  const content = '---\ntitle: "Install Proxymock"\n---\n';
  const findings = analyzeFile(
    "docs/example.mdx",
    content,
    allLines(content),
  );
  assert.equal(findings.length, 1);
  assert.equal(findings[0].match, "Proxymock");
});

test("parses only added lines from zero-context diffs", () => {
  const diff = "+++ b/docs/example.md\n@@ -2,0 +3,2 @@\n+one\n+two\n";
  assert.deepEqual(
    [...parseAddedLines(diff).get("docs/example.md")],
    [3, 4],
  );
});

test("discovers docs, partials, README, and GitHub pull request templates", () => {
  const diff = [
    "+++ b/docs/example.md",
    "@@ -0,0 +1 @@",
    "+docs",
    "+++ b/src/partials/example.mdx",
    "@@ -0,0 +1 @@",
    "+partial",
    "+++ b/README.md",
    "@@ -0,0 +1 @@",
    "+readme",
    "+++ b/.github/pull_request_template.md",
    "@@ -0,0 +1 @@",
    "+template",
    "+++ b/AGENTS.md",
    "@@ -0,0 +1 @@",
    "+internal",
    "",
  ].join("\n");
  assert.deepEqual([...parseAddedLines(diff).keys()], [
    "docs/example.md",
    "src/partials/example.mdx",
    "README.md",
    ".github/pull_request_template.md",
  ]);
});

test("ignores Docusaurus imports, JSX attributes, and comments", () => {
  const content = [
    'import Tabs from "@theme/Tabs";',
    "<Tabs",
    '  groupId="SpeedScale"',
    ">",
    "<!--",
    "Generated by Claude",
    "-->",
    "Use `SpeedScale` as test input.",
    "</Tabs>",
    "",
  ].join("\n");
  assert.equal(
    analyzeFile("docs/example.mdx", content, allLines(content)).length,
    0,
  );
});

test("ignores tilde fences while checking admonition prose", () => {
  const content = [
    "~~~text",
    "SpeedScale and Home Depot",
    "~~~",
    "",
    ":::note",
    "Install Proxymock.",
    ":::",
    "",
  ].join("\n");
  const findings = analyzeFile(
    "docs/example.mdx",
    content,
    allLines(content),
  );
  assert.equal(findings.length, 1);
  assert.equal(findings[0].rule, "product capitalization");
});
