#!/usr/bin/env bash
#
# Regenerate the MCP tools/prompts reference page from the proxymock
# binary's live tool registry, so it never drifts from the actual MCP
# server surface. Run this whenever the proxymock MCP tools change.
# The nightly "MCP docs sync" workflow runs it against each new
# proxymock release.
#
#   ./scripts/gen-mcp-docs.sh          # use `proxymock` on PATH
#   PROXYMOCK=/path/to/proxymock ./scripts/gen-mcp-docs.sh
#
# The binary comes from the speedscale repo (`PROGRAM_NAME=proxymock make
# build` in speedctl, which stamps the version) or a normal proxymock
# install (~/.speedscale/proxymock). A plain `go build` reports version
# "undefined"; set PROXYMOCK_VERSION to the tag it was built from.
#
# The version that generated the page is recorded in VERSION_FILE. The
# nightly workflow only regenerates from a release newer than it, so a
# page built from an unreleased proxymock is not rolled back. For the
# same reason this script refuses a binary older than the recorded one
# unless ALLOW_OLDER=1.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="docs/proxymock/how-it-works/mcp-tools.md"
VERSION_FILE="scripts/mcp-docs-version.txt"

# Resolve the proxymock binary: explicit override, then PATH, then the
# default install location.
BIN="${PROXYMOCK:-}"
if [ -z "${BIN}" ]; then
  if command -v proxymock >/dev/null 2>&1; then
    BIN="$(command -v proxymock)"
  elif [ -x "${HOME}/.speedscale/proxymock" ]; then
    BIN="${HOME}/.speedscale/proxymock"
  else
    echo "error: proxymock binary not found. Install it or set PROXYMOCK=/path/to/proxymock" >&2
    exit 1
  fi
fi

VERSION="${PROXYMOCK_VERSION:-}"
if [ -z "${VERSION}" ]; then
  VERSION="$("${BIN}" version --client 2>/dev/null | grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+[0-9A-Za-z.-]*' | head -n 1 || true)"
fi
if [ -z "${VERSION}" ]; then
  echo "error: cannot tell which proxymock version ${BIN} is. Set PROXYMOCK_VERSION=vX.Y.Z to the tag it was built from." >&2
  exit 1
fi

# Release part only: v2.5.1038-8-gabc123 (8 commits past v2.5.1038) -> v2.5.1038.
release_of() { printf '%s\n' "${1%%-*}"; }

if [ -f "${VERSION_FILE}" ] && [ "${ALLOW_OLDER:-}" != "1" ]; then
  recorded="$(release_of "$(tr -d '[:space:]' < "${VERSION_FILE}")")"
  current="$(release_of "${VERSION}")"
  lowest="$(printf '%s\n%s\n' "${recorded}" "${current}" | sort -V | head -n 1)"
  if [ "${current}" != "${recorded}" ] && [ "${lowest}" = "${current}" ]; then
    echo "error: ${OUT} was generated by proxymock ${recorded}, newer than ${VERSION}. Set ALLOW_OLDER=1 to roll it back anyway." >&2
    exit 1
  fi
fi

echo "Generating ${OUT} from ${BIN} (${VERSION})..." >&2
"${BIN}" mcp docs > "${OUT}"
printf '%s\n' "${VERSION}" > "${VERSION_FILE}"
echo "Done. Review the diff and commit ${OUT} and ${VERSION_FILE}." >&2
