name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install
      uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - name: build
      run: yarn build

    - name: upload main
      run: aws s3 sync build s3://docs.speedscale.com && aws cloudfront create-invalidation --distribution-id $DIST_ID --paths '/*'
      env:
        DIST_ID: E3K70OREWBZ6OV
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
