name: Build

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the AWS JWT
  contents: read # This is required for checkout

env:
  AWS_ROLE: ${{ secrets.AWS_ROLE }}
  AWS_REGION: us-east-1
  DOWNLOADS_BUCKET: downloads.speedscale.com
  DIST_ID: ${{ secrets.DIST_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: install
      uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - name: build
      run: yarn build

    - name: upload main
      run: aws s3 sync --delete  build s3://${{ env.DOWNLOADS_BUCKET }} && aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths '/*'

    - name: notify on failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"I am pretty sad right now guys. My build is failing on *'${{ github.ref_name }}'* in repository *'${{ github.repository }}'*.  Please check on me soon."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
