name: Build

on:
  push:
    branches:
      - docs-overhaul

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install
      uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - name: build
      run: yarn build


    - name: update url for overhaul preview
      run: ./tools/update_preview_base.sh overhaul

    - name: upload overhaul
      run: aws s3 sync build s3://docs-preview.speedscale.com/overhaul
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: show url
      run: echo 'http://docs-preview.speedscale.com.s3-website-us-east-1.amazonaws.com/overhaul/'
