name: PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install
      uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - name: update url for preview
      run: ./tools/update_preview_base.sh pr-${{ github.event.pull_request.number }}

    - name: build
      run: yarn build

    - name: upload preview
      run: aws s3 sync build s3://docs-preview.speedscale.com/pr-${{ github.event.pull_request.number }}
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: show url
      run: echo 'http://docs-preview.speedscale.com.s3-website-us-east-1.amazonaws.com/pr-${{ github.event.pull_request.number }}/'

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Preview available at 'http://docs-preview.speedscale.com.s3-website-us-east-1.amazonaws.com/pr-${{ github.event.pull_request.number }}/'

    - name: Create or Update comment
      uses: peter-evans/create-or-update-comment@v2
      with: 
        comment-id: ${{ steps.fc.outputs.comment-id }} # This will be empty and a new comment will be made if no comment already exists
        issue-number: ${{ github.event.pull_request.number }}
        body: Preview available at 'http://docs-preview.speedscale.com.s3-website-us-east-1.amazonaws.com/pr-${{ github.event.pull_request.number }}/'
        edit-mode: replace
