name: PR Preview Build

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install
      uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - name: build
      run: yarn build

    - name: upload preview
      run: aws s3 sync build s3://docs-preview.speedscale.com/pr-${{ pull_request.number }}
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Website URL
      run: echo 'Website: http://docs-preview.s3-website-us-east-1.amazonaws.com/pr-${{ pull_request.number }}'
