name: PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  id-token: write # This is required for requesting the AWS JWT
  contents: read # This is required for checkout
  pull-requests: write # This is required for creating a comment

env:
  AWS_ROLE: ${{ secrets.AWS_ROLE }}
  AWS_REGION: us-east-1
  DOWNLOADS_PREVIEW_BUCKET: docs-preview.speedscale.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install
      uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: update url for preview
      run: ./tools/update_preview_base.sh pr-${{ github.event.pull_request.number }}

    - name: build
      run: yarn build

    - name: upload preview
      run: aws s3 sync build s3://${{ env.DOWNLOADS_PREVIEW_BUCKET }}/pr-${{ github.event.pull_request.number }}

    - name: show url
      run: echo 'http://${{ env.DOWNLOADS_PREVIEW_BUCKET }}.s3-website-us-east-1.amazonaws.com/pr-${{ github.event.pull_request.number }}/'

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Preview available at 'http://${{ env.DOWNLOADS_PREVIEW_BUCKET }}.s3-website-us-east-1.amazonaws.com/pr-${{ github.event.pull_request.number }}/'

    - name: Create or Update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }} # This will be empty and a new comment will be made if no comment already exists
        issue-number: ${{ github.event.pull_request.number }}
        body: Preview available at 'http://${{ env.DOWNLOADS_PREVIEW_BUCKET }}.s3-website-us-east-1.amazonaws.com/pr-${{ github.event.pull_request.number }}/'
        edit-mode: replace
