name: PR Cleanup

on:
  pull_request:
    types: [closed] # merging a PR closes it
    branches: [main]

jobs:
  cleanup_docs:
    runs-on: ubuntu-latest
    steps:
    - name: Delete PR preview
      run: aws s3 rm --recursive s3://docs-preview.speedscale.com/pr-${{ github.event.pull_request.number }}
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
